### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by ginkel** [tg44/mqtt-prometheus-message-exporter#1]
AFAICS there is currently no way to provide credentials for authenticating the MQTT connection. Would be possible to add support for this?

Thanks!

**Comment by tg44** [comment]
That's right!
I think https://github.com/tg44/mqtt-prometheus-message-exporter/blob/master/src/main/scala/xyz/tg44/prometheus/Main.scala#L35 line should be configured more correctly to do the authentication.
And this is the lib: https://doc.akka.io/docs/alpakka/current/mqtt-streaming.html

If you have time, I don't think this is a big modification (as I quickly checked you have java/ruby/scala forks, so probably you can do it without much strugle).

I don't think I will have time to fix it quickly, but I will try to catch up my leftover issues/prs in the next 2 weeks.

**Comment by ginkel** [comment]
Expect a PR in the near future. ;-)
