### ISSUE TITLE
Dealing with non-numeric values

### ISSUE THREAD

**Issue by ginkel** [tg44/mqtt-prometheus-message-exporter#3]
Hi there,

I'm using this exporter to expose messages sent from zigbee2mqtt via Prometheus. For some attributes, this is straightforward as they are numeric. Others are formally a string (state = ON / OFF), but could easily be translated to 0 / 1, others are a Boolean, for which the same applies. To give you an example:

```
{
  "state": "OFF",
  "linkquality": 34,
  "last_seen": "2020-02-26T21:50:12.131Z",
  "brightness": 1,
  "color_temp": 317,
  "color": {
    "x": 0.4599,
    "y": 0.4106
  },
  "update_available": false,
  "device": {
    "friendlyName": "<redacted>",
    "model": "LED1545G12",
    "ieeeAddr": "<redacted>",
    "networkAddress": 1595,
    "type": "Router",
    "manufacturerID": 4476,
    "manufacturerName": "IKEA of Sweden",
    "powerSource": "Mains (single phase)",
    "applicationVersion": 33,
    "stackVersion": 98,
    "zclVersion": 3,
    "hardwareVersion": 1,
    "dateCode": "20190520",
    "softwareBuildID": "2.3.007"
  }
}
```

Is there currently a way to deal with `state` and `update_available`, i.e., to map those into a value in Prometheus?

Thanks!

**Comment by tg44** [comment]
Right now, nope:
https://github.com/tg44/mqtt-prometheus-message-exporter/blob/master/src/main/scala/xyz/tg44/prometheus/PatternUtils.scala#L18

I can add boolean as 0/1 and .toLowercase and on/off matches with string true/false matches also. Can you came up with useful true/false values?

So
```
"on", "On", "ON", "true", "True", "TRUE" and true -> 1
"off", "Off", "OFF", "false", "False", "FALSE" and false -> 0
```

**Comment by ginkel** [comment]
YAML is using these variants to represent a Boolean: https://yaml.org/type/bool.html

Maybe we should just use these.

**Comment by tg44** [comment]
Just committed! I think about 1 hour and it will be on dockerhub.

**Comment by ginkel** [comment]
Thanks, works like a charm! :smiley:

**Comment by ginkel** [comment]
Got an addiional use-case: zigbee2mqtt publishes a device's availability status with a value of `online` / `offline` (e.g., `zigbee2mqtt/binary_sensor.window/availability = online`), which is currently ignored by this exporter. I could imagine multiple approaches to handle this:

1. Define a value that maps to `1` (e.g., `online`) - all other values are mapped to `0`.

2. Convert the value to a label and always use `1` as the value.

@tg44 What do you think?

**Comment by tg44** [comment]
Added online/offline as a "bool".

**Comment by ginkel** [comment]
> Added online/offline as a "bool".

Thanks! Is my assumption right that the payload still needs to be JSON (which isn't the case for this very topic)? I'm trying to fix this with `tg44/mqtt-transformer` and will probably open an issue over there as I am somewhat fighting with preserving the string from a wildcard topic name match...
