### ISSUE TITLE
why I cannot get the item ?

### ISSUE THREAD

**Issue by hanjie0** [tg44/mqtt-prometheus-message-exporter#8]
Dear

Here is the data in my mqtt broker.

{
"app": {
"moteeui": "32010124131300ed",
"Class": 0,
"type": "payload",
"confirmed": true,
"userdata": {
"seqno": 1617,
"port": 2,
"payload": "qmcBAO0LAwBEAAAAAAAAAP4=",
"motetx": {
"freq": 472,
"modu": "LORA",
"datr": "SF7BW125",
"codr": "4/5",
"adr": false
}
},
"gwrx": [
{
"eui": "34010a44124e0025",
"time": "",
"timefromgateway": false,
"chan": 3,
"rfch": 1,
"rssi": -67,
"lsnr": 10
},
{
"eui": "34010a44124e0068",
"time": "",
"timefromgateway": false,
"chan": 3,
"rfch": 1,
"rssi": -34,
"lsnr": 8.8
}
]
}
}
in which, the app/userdata/payload is the mandatory item I need.
and my topic is mdata/400101000b000c06/upALL .
the device id is 400101000b000c06

Here "payload": "qmcBAO0LAwBEAAAAAAAAAP4=". accroding to your README, it seems the string cannot be translated to 0/1 will be dropped.  it is why I can not get it ?

**Comment by tg44** [comment]
Exactly. Prometheus does not really handle string. We can add them as labels, but it is [not a wise decision](https://prometheus.io/docs/practices/naming/#labels). So I decided to left out everything that is not numerical, or cannot be converted to numerical.

If this value is in fact a label, you should restructure the payload and move this to a key. (You can do this by https://github.com/tg44/mqtt-transformer for example.) Also, for hexa numbers, or the "4/5" field you probably want to transform the payload before you feed it to the exporter.

This tool was made for a really narrow purpose, and you can use other tools/apps to extend its capabilities for much wider use-cases.

**Comment by tg44** [comment]
I close this bcs of inactivity.
